name: Run unit tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for PostgreSQL to start
        run: |
          dockerize -wait tcp://localhost:5432 -timeout 1m

      - name: Run database migrations
        run: python manage.py migrate

      - name: Run unit tests
        run: python test_user.py
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/mydb
