name: Run unit tests

on:
  workflow_dispatch:
  
jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Create database
        run: python create.py
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: ${{ secrets.SECRET_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run unit tests
        run: python test_user.py
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: ${{ secrets.SECRET_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
